const express = require("express");
const router = express.Router();
const { requireAuth, requireAdmin, requireCsrfToken } = require("./middleware");

module.exports = function (db) {
  // Link Discord account to game player
  router.post("/link-discord", requireAuth, requireCsrfToken, async (req, res) => {
    const { discordUserId, discordUsername } = req.body;
    if (!discordUserId || !discordUsername) {
      return res.status(400).json({ error: "discordUserId and discordUsername required" });
    }

    try {
      // Check if Discord ID is already linked
      const existing = await db.get(
        "SELECT player_id FROM discord_links WHERE discord_user_id = $1",
        [discordUserId]
      );

      if (existing && existing.player_id !== req.player.playerId) {
        return res.status(409).json({ error: "This Discord account is already linked to another player" });
      }

      // Check if player already has a Discord link
      const playerLink = await db.get(
        "SELECT id FROM discord_links WHERE player_id = $1",
        [req.player.playerId]
      );

      if (playerLink) {
        // Update existing link
        await db.run(
          "UPDATE discord_links SET discord_user_id = $1, discord_username = $2, updated_at = $3 WHERE player_id = $4",
          [discordUserId, discordUsername, Math.floor(Date.now() / 1000), req.player.playerId]
        );
      } else {
        // Create new link
        await db.run(
          "INSERT INTO discord_links (player_id, discord_user_id, discord_username) VALUES ($1, $2, $3)",
          [req.player.playerId, discordUserId, discordUsername]
        );
      }

      res.json({ ok: true, message: `Linked Discord account @${discordUsername}` });
    } catch (err) {
      console.error("[discord] Link error:", err);
      res.status(500).json({ error: "Failed to link Discord account" });
    }
  });

  // Unlink Discord account from game player
  router.post("/unlink-discord", requireAuth, requireCsrfToken, async (req, res) => {
    try {
      await db.run("DELETE FROM discord_links WHERE player_id = $1", [req.player.playerId]);
      res.json({ ok: true, message: "Discord account unlinked" });
    } catch (err) {
      console.error("[discord] Unlink error:", err);
      res.status(500).json({ error: "Failed to unlink Discord account" });
    }
  });

  // Get Discord link status for current player
  router.get("/link-status", requireAuth, async (req, res) => {
    try {
      const link = await db.get(
        "SELECT discord_user_id, discord_username, linked_at FROM discord_links WHERE player_id = $1",
        [req.player.playerId]
      );

      if (!link) {
        return res.json({ linked: false });
      }

      res.json({
        linked: true,
        discordUserId: link.discord_user_id,
        discordUsername: link.discord_username,
        linkedAt: new Date(link.linked_at * 1000).toISOString(),
      });
    } catch (err) {
      console.error("[discord] Link status error:", err);
      res.status(500).json({ error: "Failed to get link status" });
    }
  });

  // Verify a link token generated by the Discord bot's !link command
  router.post("/verify-token", requireAuth, requireCsrfToken, async (req, res) => {
    const { token } = req.body;
    if (!token) {
      return res.status(400).json({ error: "token required" });
    }

    try {
      const now = Math.floor(Date.now() / 1000);
      const record = await db.get(
        "SELECT * FROM discord_link_tokens WHERE token = $1 AND expires_at > $2",
        [token.trim().toUpperCase(), now]
      );

      if (!record) {
        return res.status(400).json({ error: "Invalid or expired verification code" });
      }

      // Verify the game username matches the logged-in player
      const player = await db.get("SELECT username FROM players WHERE id = $1", [req.player.playerId]);
      if (!player || player.username.toLowerCase() !== record.game_username.toLowerCase()) {
        return res.status(403).json({ error: "This code was generated for a different game account" });
      }

      // Check if Discord ID is already linked to another player
      const existing = await db.get(
        "SELECT player_id FROM discord_links WHERE discord_user_id = $1",
        [record.discord_user_id]
      );
      if (existing && existing.player_id !== req.player.playerId) {
        return res.status(409).json({ error: "This Discord account is already linked to another player" });
      }

      // Upsert the link
      const playerLink = await db.get("SELECT id FROM discord_links WHERE player_id = $1", [req.player.playerId]);
      if (playerLink) {
        await db.run(
          "UPDATE discord_links SET discord_user_id = $1, discord_username = $2, updated_at = $3 WHERE player_id = $4",
          [record.discord_user_id, record.discord_username, now, req.player.playerId]
        );
      } else {
        await db.run(
          "INSERT INTO discord_links (player_id, discord_user_id, discord_username) VALUES ($1, $2, $3)",
          [req.player.playerId, record.discord_user_id, record.discord_username]
        );
      }

      // Consume the token
      await db.run("DELETE FROM discord_link_tokens WHERE token = $1", [record.token]);

      res.json({ ok: true, discordUsername: record.discord_username });
    } catch (err) {
      console.error("[discord] Verify token error:", err);
      res.status(500).json({ error: "Failed to verify token" });
    }
  });

  // Admin: Configure Discord channel sync
  router.post("/admin/configure-channel", requireAdmin, requireCsrfToken, async (req, res) => {
    const { channelId, channelName, gameRoom, syncBothDirections } = req.body;
    if (!channelId || !channelName || !gameRoom) {
      return res.status(400).json({ error: "channelId, channelName, and gameRoom required" });
    }

    try {
      const existing = await db.get(
        "SELECT id FROM discord_sync_config WHERE channel_id = $1",
        [channelId]
      );

      if (existing) {
        // Update existing config
        await db.run(
          "UPDATE discord_sync_config SET channel_name = $1, game_room = $2, sync_both_directions = $3, updated_at = $4 WHERE channel_id = $5",
          [channelName, gameRoom, syncBothDirections ? 1 : 0, Math.floor(Date.now() / 1000), channelId]
        );
      } else {
        // Create new config
        await db.run(
          "INSERT INTO discord_sync_config (channel_id, channel_name, game_room, sync_both_directions) VALUES ($1, $2, $3, $4)",
          [channelId, channelName, gameRoom, syncBothDirections ? 1 : 0]
        );
      }

      // Reload configs in discord bot
      console.log(`📡 Discord channel sync config updated: #${channelName} <-> ${gameRoom}`);

      res.json({ ok: true, message: `Configured Discord #${channelName} to sync with ${gameRoom}` });
    } catch (err) {
      console.error("[discord] Config error:", err);
      res.status(500).json({ error: "Failed to configure channel" });
    }
  });

  // Admin: Disable/enable channel sync
  router.post("/admin/toggle-channel", requireAdmin, requireCsrfToken, async (req, res) => {
    const { channelId, enabled } = req.body;
    if (!channelId || enabled === undefined) {
      return res.status(400).json({ error: "channelId and enabled required" });
    }

    try {
      await db.run(
        "UPDATE discord_sync_config SET enabled = $1, updated_at = $2 WHERE channel_id = $3",
        [enabled ? 1 : 0, Math.floor(Date.now() / 1000), channelId]
      );

      res.json({ ok: true, message: `Channel sync ${enabled ? "enabled" : "disabled"}` });
    } catch (err) {
      console.error("[discord] Toggle error:", err);
      res.status(500).json({ error: "Failed to toggle channel" });
    }
  });

  // Admin: Get all sync configs
  router.get("/admin/configs", requireAdmin, async (req, res) => {
    try {
      const configs = await db.all("SELECT * FROM discord_sync_config ORDER BY created_at DESC");
      res.json({ configs });
    } catch (err) {
      console.error("[discord] Get configs error:", err);
      res.status(500).json({ error: "Failed to get configs" });
    }
  });

  // Admin: Get linked Discord users
  router.get("/admin/linked-users", requireAdmin, async (req, res) => {
    try {
      const links = await db.all(`
        SELECT d.id, d.discord_user_id, d.discord_username, d.linked_at, p.username as game_username
        FROM discord_links d
        JOIN players p ON d.player_id = p.id
        ORDER BY d.linked_at DESC
      `);
      res.json({ links });
    } catch (err) {
      console.error("[discord] Get links error:", err);
      res.status(500).json({ error: "Failed to get linked users" });
    }
  });

  return router;
};
