export const REGION_META = {
  dwarf: { name: 'The Iron Holds', color: '#8B6914', stroke: '#c8962a', icon: '', x: 150, y: 200, w: 200, h: 180 },
  high_elf: { name: 'The Silverwood', color: '#1a4a2e', stroke: '#4caf82', icon: '', x: 420, y: 80, w: 220, h: 200 },
  orc: { name: 'The Bloodplains', color: '#4a1010', stroke: '#e05c5c', icon: '', x: 560, y: 300, w: 200, h: 200 },
  dark_elf: { name: 'The Underspire', color: '#1a1030', stroke: '#9d4edd', icon: '', x: 380, y: 340, w: 180, h: 200 },
  human: { name: 'The Heartlands', color: '#1a2a10', stroke: '#8fb84a', icon: '', x: 200, y: 380, w: 200, h: 180 },
  dire_wolf: { name: 'The Ashfang Wilds', color: '#0d1a20', stroke: '#4a8fb8', icon: '', x: 60, y: 390, w: 160, h: 170 },
  vampire: { name: 'The Nightfall Marshes', color: '#2a0a1a', stroke: '#8b1a4a', icon: '', x: 420, y: 320, w: 180, h: 170 },
  ogre: { name: 'The Cinder Reaches', color: '#3a2410', stroke: '#b8752a', icon: '', x: 780, y: 380, w: 190, h: 180 },
  wood_elf: { name: 'The Emerald Vale', color: '#0f3018', stroke: '#3fae5c', icon: '', x: 700, y: 210, w: 190, h: 180 },
};

export const REGION_BONUSES = {
  dwarf: 'Improved construction speed',
  high_elf: 'Increased mana production',
  orc: 'Superior military strength',
  dark_elf: 'Enhanced stealth and covert ops',
  human: 'Better economy',
  dire_wolf: 'Superior military strength',
  vampire: 'Night combat specialization',
  ogre: 'Brute strength and intimidation',
  wood_elf: 'Nature attunement and stealth',
};

export const RACE_LORE = {
  dwarf: {
    title: 'Dwarves of The Iron Holds',
    icon: '',
    lore: 'Deep beneath the mountain roots, Dwarven civilisation predates all others in recorded history. Their citadels are not merely fortresses — they are cities of impossible scale, carved across generations by engineers who see rock as other races see clay. The Dwarves do not conquer land; they improve it, smelt it, and sell it back to you at a profit.',
    strengths: [
      'Master builders — extremely fast construction speed',
      'Powerful economy and gold generation',
      'Superior war machines and siege engines',
      'Elite engineer training programs',
    ],
    weaknesses: [
      'Very weak magical capabilities',
      'Below-average resource research',
      'Limited surface exploration range',
    ],
    heroes: ['Siegebreaker', 'Forge Lord', 'Stonelord'],
    special: 'Level 25+ engineers can solo-crew war machines',
    playstyle: 'Economy and fortress play. Turtle behind walls, stockpile gold, outlast everyone.',
    color: '#c8962a',
  },
  high_elf: {
    title: 'High Elves of The Silverwood',
    icon: '',
    lore: 'Ageless and arch, the High Elves have spent millennia convinced they are the chosen custodians of arcane knowledge. Whether or not this is true is debated; that they produce more magical energy per mage than any other race is not. They grow slowly and build sparsely, but a High Elf mage at level 100 is worth ten of any other race.',
    strengths: [
      'Vast magical reserves and research potential',
      'Can produce extra scrolls during crafting',
      'Highly efficient mage and cleric training',
      'Substantial mana generation per cycle',
    ],
    weaknesses: [
      'Significant military fragility',
      'Very limited housing capacity',
      'Minimal population growth rate',
      'Severely impacted by overcrowding',
    ],
    heroes: ['Archmage', 'Lunar Sentinel', 'Mage-King'],
    special: 'Level 25+ mages produce 2 scrolls per craft instead of 1',
    playstyle: 'Magic dominance. Stack mages, craft scrolls fast, debuff enemies with tier-3 spells.',
    color: '#4caf82',
  },
  orc: {
    title: 'Orcs of The Bloodplains',
    icon: '',
    lore: 'The Orcs have never needed a reason to go to war. The Bloodplains have been theirs since before the other races learned to write, and they intend to keep them — by force, by treaty, and by sheer weight of bodies. An Orc kingdom at full tilt is a roaring machine of meat and momentum that only a High Elf spell battery or a Dwarven fortress can hope to outlast.',
    strengths: [
      'Formidable front-line fighters',
      'Significant military power bonuses',
      'Passive troop generation from masters',
      'Robust economic structure',
    ],
    weaknesses: [
      'Poor investment in research',
      'Virtually no magical aptitude',
      'Slower construction progress',
    ],
    heroes: ['Warlord', 'High Chieftain', 'Warshaman'],
    special: 'Level 25+ fighters passively generate free trainees each turn',
    playstyle: 'Blitzkrieg. Rush military, attack early, snowball fighter count with passive generation.',
    color: '#e05c5c',
  },
  dark_elf: {
    title: 'Dark Elves of The Underspire',
    icon: '',
    lore: 'No one knows how many Dark Elves there are. That is precisely how they like it. Operating from a vast underground network of city-warrens and shadow markets, they wage war through proxy, poison, and precision. By the time you know a Dark Elf kingdom is attacking, half your thieves are already dead.',
    strengths: [
      'Unrivaled covert operations and stealth',
      'Lethal units specialized in assassination',
      'Trained rangers for high-risk scouting',
      'Excellent global exploration',
    ],
    weaknesses: [
      'Fragile military units in open battle',
      'Modest economic output',
      'Limited housing availability',
    ],
    heroes: ['Assassin', 'Void Weaver', 'Shadowmaster'],
    special: 'Level 25+ ninjas perform silent assassinations — hidden from news reports',
    playstyle: 'Shadow warfare. Drain enemy gold and research with thieves, assassinate key units, spy constantly.',
    color: 'var(--accent1)',
  },
  human: {
    title: 'Humans of The Heartlands',
    icon: '',
    lore: 'Humans are not the strongest, the fastest, the most magical, or the most cunning. What they are is relentless. They breed quickly, adapt faster than any other race, and build institutions that outlast individual heroes. A Human kingdom in the mid-game is deceptively dangerous — by the time it shows its teeth, it has already won.',
    strengths: [
      'Versatile and adaptable in all military areas',
      'Exceptional population growth speed',
      'Access to powerful happiness-boosting clerics',
      'Strong exploration initiatives',
    ],
    weaknesses: [
      'Lacks specialization in any single discipline',
      'Requires careful strategic balance',
    ],
    heroes: ['Paladin', 'Grand Chancellor', 'High Consul'],
    special: 'Level 25+ clerics radiate a healing aura that restores kingdom happiness',
    playstyle: 'Flexible all-rounder. Strong in long games where adaptation outweighs specialisation.',
    color: '#8fb84a',
  },
  dire_wolf: {
    title: 'Dire Wolves of The Ashfang Wilds',
    icon: '',
    lore: 'The Dire Wolves do not build kingdoms — they claim territory. Their settlements are mobile, their supply chains are their rangers, and their economy is whatever they can take from the land before moving on. They are the dominant military power in Narmir, and they know it. Everyone else knows it too.',
    strengths: [
      'Most powerful combatants in the realm',
      'Elite rangers with rapid expedition cycle',
      'Overwhelming natural military strength',
      'Resilient explorers with minimal losses',
      'Massive housing capacity from tribal lands',
    ],
    weaknesses: [
      'Significant economic struggles',
      'Extremely limited magical knowledge',
      'Lack of formal research systems',
      'High logistical upkeep for armies',
    ],
    heroes: ['Alpha Pack-Leader', 'Storm Howler', 'Blood Shaman'],
    special: 'Level 25+ rangers execute expeditions at a much faster pace',
    playstyle: 'Raid and conquest. Hit fast, take land, use rangers for gold when not at war.',
    color: '#4a8fb8',
  },
  vampire: {
    title: 'Vampires of The Sanguine Spires',
    icon: '',
    lore: 'Ancient and immortal, the Vampires view the other races as little more than cattle for their blood-feasts. From their dark spires, they command armies of thralls and necromantic soldiers. They are masters of the night, but the sun is their undoing.',
    strengths: [
      'Devastating efficiency during night hours',
      'Recruits fallen enemies into their army',
      'Rapid combat experience gain',
      'Effective daytime stealth and evasion',
    ],
    weaknesses: [
      'Significant combat penalties in daylight',
      'Limited natural economic systems',
      'Perpetual need for population consumption',
    ],
    heroes: ['Night Lord', 'Sanguine Oracle', 'Blood Matriarch'],
    special: 'Level 25+ Infiltrators have significantly higher theft and sabotage success',
    playstyle: 'Necromantic conquest. Dominate the night, harvest souls, and convert the fallen into your eternal army.',
    color: '#b43c00',
  },
  ogre: {
    title: 'Ogres — Unmatched Warriors',
    icon: '',
    lore: 'Massive, powerful beings of raw strength and primal fury. Ogres excel in combat like no other race. However, their lack of intellectual curiosity makes them poor scholars — research and magic are foreign to their nature. An Ogre kingdom thrives on military dominance and conquest, not academic pursuit.',
    strengths: [
      'Ogre Warriors deal +25% attack damage',
      'Superior melee combat capabilities',
      'Intimidating military presence',
    ],
    weaknesses: [
      'Research progresses 30% slower',
      'Magic production 25% reduced',
      'Limited by their warrior culture',
    ],
    heroes: ['Arcane Master', 'Blood Lord', 'Brute Lord'],
    special: '★ Coming Soon — Special Ogre Warrior unit with enhanced combat damage',
    playstyle: 'Aggressive military dominance. Build armies quickly, overwhelm enemies through superior firepower.',
    color: '#8b572a',
  },
  wood_elf: {
    title: 'Wood Elves — Master Explorers',
    icon: '',
    lore: 'Nomadic forest dwellers with an unmatched ability to read terrain and discover hidden lands. Their tracking skills and intimate knowledge of nature allow them to find more land with fewer resources and less time. However, their preference for subterfuge and scouting makes them weak in direct combat.',
    strengths: [
      '+75% land discovered per expedition',
      '-40% expedition resource cost',
      '-40% expedition completion time',
      'Fastest way to expand territory',
    ],
    weaknesses: [
      'Combat troops deal 25% less damage',
      'Rely on tactics and territory, not strength',
      'Vulnerable to direct military assault',
    ],
    heroes: ['Scout Master', 'Ranger Lord', 'Wildshaper'],
    special: '★ Coming Soon — Unparalleled expedition bonuses for rapid territorial expansion',
    playstyle: 'Territorial expansion through superior exploration. Discover land others cannot reach.',
    color: '#22c55e',
  },
};
